### ISSUE TITLE
Authentication is not working because "link is not working"

### ISSUE THREAD

**Issue by georgobermayr** [immrl/meteor-account-wechat#1]
Hi,

I'm not able to make the login with WeChat work: The pop-up window opens ofter clicking the login button but it just says:
![bildschirmfoto 2016-09-14 um 10 31 27](https://cloud.githubusercontent.com/assets/8470615/18505201/779b996c-7a66-11e6-88a5-699060c0b416.png)
该链接无法访问 seems to mean that the "link is not working" …

We had our app (via our Chinese distributor) registered at https://open.weixin.qq.com and the Login permission has been granted by WeChat. The callback URL is set to <domain>/_oauth/wechat
Any idea why this is not working?

Thank you,
Georg

**Comment by fclcode** [comment]
This error is usually due to callback url mismatch. Please double check the callback url set in https://open.weixin.qq.com. Just set the domain and its port if any, there is no need to identify the subsequent path.
Note: if your app is under development, set the callback url to http://localhost:port and open your app by  http://localhost:port . The url you are using in the browser should be exactly the same with what you've set in https://open.weixin.qq.com.

**Comment by georgobermayr** [comment]
Yeah, removing /_oauth/wechat from the callback URL seemed to do the trick!
Maybe you should remove that from the documentation because it only works without the subsequent path.
Thank you!
